---
title: "8_rna_velocity"
---
```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(SeuratWrappers)
  library(BSgenome.Nfurzeri.NCBI.Nfu20140520.custom)
  library(tidyverse)
  library(reticulate)
})



#import helper functions
source("C:/Users/Christopher He/OneDrive/UCSF/Singh Lab/diapause-sc-multiome/code/helper_functions.R")

#set output and figure directories
outs_dir <- "../results_all/"
fig_dir <- "../results_all/"
```
#Load Seurat Object
```{r}
so <- readRDS("../results_all/so_wnn.rds")
```


```{r}
so$barcode <- colnames(so)
so$UMAP_1 <- so@reductions$umap@cell.embeddings[,1]
so$UMAP_2 <- so@reductions$umap@cell.embeddings[,2]
so$UMAP_wnn_1 <- so@reductions$umap_wnn@cell.embeddings[,1]
so$UMAP_wnn_2 <- so@reductions$umap_wnn@cell.embeddings[,2]

write.csv(so@meta.data, file=paste0(outs_dir, 'metadata.csv'), quote=F, row.names=F)

rm(so)
gc()
# # write expression counts matrix
# library(Matrix)
# counts_matrix <- GetAssayData(seurat_obj, assay='RNA', slot='counts')
# writeMM(counts_matrix, file=paste0(out_data_dir, 'counts.mtx'))
# 
# # write dimesnionality reduction matrix, in this example case pca matrix
# write.csv(seurat_obj@reductions$pca@cell.embeddings, file='pca.csv'), quote=F, row.names=F)
# 
# # write gene names
# write.table(
#   data.frame('gene'=rownames(counts_matrix)),file='gene_names.csv',
#   quote=F,row.names=F,col.names=F
# )
```


Note: Using python version through reticulate. scVelo and multiVelo were installed in the multiome-velocyto conda environment
```{r}
reticulate::use_condaenv("multiome-velocyto")
```

```{python}
import os
import scipy
import numpy as np
import pandas as pd
import scanpy as sc
import scvelo as scv
import multivelo as mv
import matplotlib.pyplot as plt
from pathlib import Path
```

```{python}
sc.settings.cachedir = Path('../results_all/cache')
scv.settings.verbosity = 3
scv.settings.presenter_view = True
scv.set_figure_params('scvelo')
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 200)
np.set_printoptions(suppress=True)
```

## Reading in unspliced and spliced countsïƒ
```{python}
adata_rna = sc.read("../aggr_batch1-3/velocyto/velocyto_combined.loom", cache=True)

#rename barcodes to seurat format ("[barcode]-n" where n correspondes to sample)
suffixes = sum([[f"-{i}"] * n for i, n in enumerate([10177, 9774, 10510, 6575, 10736, 5993, 17082, 12245, 7928, 12501, 20000, 12563], start=1)], [])
adata_rna.obs_names = [x.split(':')[1][:-1] for x in adata_rna.obs_names]

#append "-n" suffix to each barcode
adata_rna.obs_names = [a + b for a, b in zip(adata_rna.obs_names, suffixes)]
```

```{python}
#read in metadata table from seurat object
cell_meta = pd.read_csv("../results_all/metadata.csv")

#filter barcodes in seurat object
barcodes = cell_meta['barcode']
adata_rna = adata_rna[adata_rna.obs_names.isin(barcodes)].copy()

#add metadata to adata object
adata_rna.obs = cell_meta
```

```{python}
# Top 1000 variable genes are used for downstream analyses.
scv.pp.filter_and_normalize(adata_rna, min_shared_counts=10, n_top_genes=1000)
```

```{python}
# subset dev cells
adata_dev = adata_rna[adata_rna.obs['timepoint_group'].isin(['dev'])]
adata_dev
```

##Preprocessing the ATAC counts
```{python}
adata_atac = sc.read_10x_mtx('../aggr_batch1-3/filtered_feature_bc_matrix/', var_names='gene_symbols', cache=True, gex_only=False)
adata_atac = adata_atac[:,adata_atac.var['feature_types'] == "Peaks"]
```

```{python}
adata_atac = mv.aggregate_peaks_10x(adata_atac,
                                    '../aggr_batch1-3/atac_peak_annotation.tsv',
                                    '../aggr_batch1-3/feature_linkage.bedpe')
                                    
```
```{python}
adata_atac_X_copy = adata_atac.X.A
```

```{python}
plt.hist(adata_atac.X.sum(1), bins=100, range=(0, 100000));
```



```{r}
library(reticulate)
table(py$suff)

```


