---
title: "9_neuronal_subclustering"
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(SeuratWrappers)
  library(BSgenome.Nfurzeri.NCBI.Nfu20140520.custom)
  library(tidyverse)
})



#import helper functions
source("C:/Users/Christopher He/OneDrive/UCSF/Singh Lab/diapause-sc-multiome/code/helper_functions.R")

#set output and figure directories
outs_dir <- "../results_all/"
fig_dir <- "../results_all/"
```

```{r}
so <- readRDS("../results_all/so_wnn.rds")
```

```{r}
#subset cells annotated as neuronal by both RNA and ATAC
rna_neurons <- WhichCells(
  so,
  expression = annotation_broad %in% c(
    "neuron_sema3c", "neuron_dscam", "neuron", 
    "midbrain_hindbrain", "neuron_progenitor",
    "differentiating_neuron", "spinal_cord", "neuron_progenitor",
    "midbrain_hindbrain_pax2/5_en1/2", "midbrain_hindbrain_wnt1/lmx1b",
    "telencephalon/optic_cup"
  )
)

atac_neurons <- WhichCells(
  so,
  expression = annotation_ATAC_broad %in% c(
    "brain", "spinal_cord", "neuron", 
    "midbrain_hindbrain", "neuron_progenitor",
    "telencephalon/optic_cup", "floor_plate", "neuron_dscam",
    "neuron_neurod1"
  )
)

so_neurons <- subset(
  so,
  cells = intersect(rna_neurons, atac_neurons)
)

```

```{r}
so_neurons <- runSeuratRNAProcessing(so_neurons)
```


```{r}
DimPlot(so_neurons, reduction = "umap", group.by = "timepoint_group", cols = colors_timepoints)
DimPlot(so_neurons, reduction = "umap", group.by = "annotation_broad", cols = colors_broad, label = T)
DimPlot(so_neurons, reduction = "umap")

```

```{r}
DefaultAssay(so_neurons) <- "ATAC"
so_neurons <- FindTopFeatures(so_neurons, min.cutoff = 'q0')
so_neurons <- RunTFIDF(so_neurons)
so_neurons <- RunSVD(so_neurons)
```

```{r}
# build a joint neighbor graph using both assays
so_neurons <- FindMultiModalNeighbors(
  object = so_neurons,
  reduction.list = list("pca", "lsi"), 
  dims.list = list(1:30, 1:30),
  verbose = TRUE
)

# build a joint UMAP visualization
so <- RunUMAP(
  object = so,
  nn.name = "weighted.nn",
  assay = "RNA",
  reduction.name = "umap_wnn",
  verbose = TRUE
)


DimPlot(so, reduction = "umap_wnn", label = T, cols = colors_broad) + NoLegend()
DimPlot(so, reduction = "umap_wnn", group.by = "timepoint_group")

saveRDS(so, "../results_all/so_wnn.rds")
```
```{r}
# preprocess RNA
DefaultAssay(so_neurons) <- "RNA"

so_neurons <- NormalizeData(so_neurons)
so_neurons <- FindVariableFeatures(so_neurons)
so_neurons <- ScaleData(so_neurons) # not scaled for consistency with scVelo (optionally, use SCTransform)
so_neurons <- RunPCA(so_neurons, verbose = FALSE)
so_neurons <- RunUMAP(so_neurons, dims = 1:30, reduction.name = "umap.rna") # optional
```


```{r}
# preprocess ATAC
DefaultAssay(so_neurons) <- "ATAC"
so_neurons <- RunTFIDF(so_neurons)
so_neurons <- FindTopFeatures(so_neurons, min.cutoff = 'q0')
so_neurons <- RunSVD(so_neurons)
so_neurons <- RunUMAP(so_neurons, reduction = 'lsi', dims = 2:30, reduction.name = "umap.atac") # optional
```

```{r}
DimPlot(so_neurons, reduction = "umap.rna", group.by = "timepoint_group", cols = colors_timepoints)
DimPlot(so_neurons, reduction = "umap.rna", group.by = "annotation_broad", cols = colors_broad, label = T)

DimPlot(so_neurons, reduction = "umap.atac", group.by = "timepoint_group", cols = colors_timepoints)
DimPlot(so_neurons, reduction = "umap.atac", group.by = "annotation_broad", cols = colors_broad, label = T)

```

```{r}
# find weighted nearest neighbors
so_neurons <- FindMultiModalNeighbors(so_neurons, reduction.list = list("pca", "lsi"), dims.list = list(1:30, 2:30))
so_neurons <- RunUMAP(so_neurons, nn.name = "weighted.nn", reduction.name = "wnn.umap") # optional
```

```{r}

DimPlot(so_neurons, reduction = "wnn.umap", group.by = "timepoint_group", cols = colors_timepoints)
DimPlot(so_neurons, reduction = "wnn.umap", group.by = "annotation_broad", cols = colors_broad, label = T)
DimPlot(so_neurons, reduction = "wnn.umap", group.by = "annotation_ATAC_broad", cols = colors_broad, label = T)

```


```{r}
saveRDS(so_neurons, paste0(outs_dir, "so_neurons.rds"))
```

