---
title: "figure1"
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(Signac)
  library(BSgenome.Nfurzeri.NCBI.Nfu20140520.custom)
  library(tidyverse)
})

source("C:/Users/Christopher He/OneDrive/UCSF/Singh Lab/diapause-sc-multiome/code/helper_functions.R")
```

```{r}
outs_dir <- "../results_all/"
fig_dir <- "../figures/figure1/"
```

```{r}
so <- readRDS("../results_all/so_dual_annotated.rds")
```

# Figure 1B
```{r}
timepoint_cols <- c("#E496EF","#800080", "#C6DBEF", "#C6DBEF", "#6BAED6", "#2171B5", "#08306B", "#FD8D3C")

#RNA UMAPs
p1 <- DimPlot(so, group.by = "annotation_broad", reduction = "umap", label = F, cols = colors_broad) + NoLegend() + NoAxes()
SaveFigure(p1, "1B_umap_annot_rna", type = "png", width = 10, height = 10, res = 300)

p2 <- DimPlot(so, group.by = "timepoint", reduction = "umap", label = F, cols = timepoint_cols) + NoLegend() + NoAxes()
SaveFigure(p2, "1B_umap_timepoint_rna", type = "png", width = 10, height = 10, res = 300)

#ATAC UMAPs
p3 <- DimPlot(so, group.by = "annotation_ATAC_broad", reduction = "umap_ATAC", label = F, cols = colors_broad) + NoLegend() + NoAxes()
SaveFigure(p3, "1B_umap_annot_atac", type = "png", width = 10, height = 10, res = 300)

p4 <- DimPlot(so, group.by = "timepoint", reduction = "umap_ATAC", label = F, cols = timepoint_cols) + NoLegend() + NoAxes()
SaveFigure(p4, "1B_umap_timepoint_atac", type = "png", width = 10, height = 10, res = 300)
```
# Figure 1C
```{r}
#rna dot plot
marker_genes_final <- c(
  'col5a1',
  'junb (1 of 2)',
  'pmp22 (1 of 3)',
  'nid2',
  'egfl7',
  'myh15',
  'sema3c',
  'dscam',
  'elavl3',
  'dll1 (1 of 4)',
  'hoxd4 (2 of 2)',
  'cldn5',
  'pax5',
  'reps2',
  'ntrk2 (2 of 2)',
  'epcam',
  'erbb3 (1 of 2)',
  'cldn4 (12 of 20)',
  'dspp (4 of 4)',
  'cldn7 (1 of 2)',
  'rbpms (1 of 2)',
  'p4hb (2 of 3)',
  'pmel (2 of 2)',
  'col8a1 (1 of 3)',
  'fry (1 of 2)',
  'myl4 (1 of 2)',
  'clec10a (1 of 4)'
)

marker_genes <- translate(marker_genes_final, from = "N. furzeri Final Symbol", to = "N. furzeri (NCBI)")
DefaultAssay(so) <- "RNA"
p <- DotPlot(so, features = marker_genes, group.by = "annotation_broad") + RotatedAxis() + scale_x_discrete(labels=marker_genes_final)
SaveFigure(p, "1C_marker_dotplot", type = "png", width = 15, height = 8, res = 300)
```


```{r}
#atac dotplot
marker_genes_final <- c(
  'ptprn2 (2 of 3)',
  'hoxb2 (2 of 2)', 
  'dscaml1 (1 of 2)',
  'pax3 (2 of 2)',
  'bmpr1b (1 of 2)',
  'sox2 (2 of 3)',
  'adgra2',
  'cadps2',
  'mnat1',
  'prpsap1 (1 of 2)',
  'angpt1 (2 of 2)',
  'dgkk',
  'wnt6',
  'tgfbr3 (2 of 3)',
  'rbm47',
  'inpp5a (1 of 2)',
  'sox10 (2 of 2)',
  'sptb',
  'otol1 (2 of 3)',
  'dscam (1 of 5)',
  'neurod1'
)
marker_genes <- translate(marker_genes_final, from = "N. furzeri Final Symbol", to = "N. furzeri (NCBI)")

p <- DotPlot(so, features = marker_genes, assay = "gene_activity", group.by = "annotation_ATAC_broad") + RotatedAxis() + scale_x_discrete(labels=marker_genes_final)
SaveFigure(p, "1C_marker_dotplot_gene_activity", type = "png", width = 15, height = 8, res = 300)

```
# Figure 1D - umaps split by timetpoint
```{r}

#####TODO: COLORS NEED ADJUSTING####


meta <- so@meta.data
meta$barcodes <- rownames(meta)


meta <- meta %>%
  group_by(timepoint, annotation_broad) %>%
  summarize(barcodes = list(barcodes), .groups = 'drop')

# Split the dataframe by sample
sample_lists <- split(meta, meta$timepoint)

# Create a list for each sample with barcodes grouped by cell type
result <- lapply(sample_lists, function(x) {
  setNames(x$barcodes, x$annotation_broad)
})

for(i in 1:8){
  p <- DimPlot(so, group.by = "annotation_broad", cells.highlight = result[[i]],
                             cols.highlight = "blue",
                             reduction = "umap", label = F, cols = "grey") + NoLegend() + NoAxes()
  SaveFigure(p, paste0("1D_", levels(so$timepoint)[i], "_umap"), type = "png", width = 10, height = 10, res = 300)

}
```

